# 默认使用开发配置
spring:
  profiles:
    active: dev
    
#配置mybatis参数
mybatis:
  mapper-locations: classpath:mapper/*.xml
  
--- 
  
#开发配置
spring:
  profiles: dev

  datasource: 
    url: jdbc:mysql://localhost:3306/demo?autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: wxh870914 